const ratioSelectElement = document.getElementById("ratio");
const baseFontSizeInputElement = document.getElementById("base-font-size");
const darkModeToggleElement = document.getElementById("dark-mode-toggle");
const fontFamilySelectElement = document.getElementById("font-family");
const ratioValueInputElement = document.getElementById("ratio-value");

ratioSelectElement.addEventListener("change", (event) => {
  const selectedRatio = parseFloat(event.target.value);
  console.log(selectedRatio);
  if (!isNaN(selectedRatio) && selectedRatio > 0) {
    document.documentElement.style.setProperty("--multiplier", selectedRatio);
    ratioValueInputElement.value = selectedRatio.toFixed(2);
  }
  ratioValueInputElement.disabled = selectedRatio !== 1.15;
});

baseFontSizeInputElement.addEventListener("change", (event) => {
  const baseFontSize = parseFloat(event.target.value);
  if (!isNaN(baseFontSize) && baseFontSize > 0) {
    document.documentElement.style.fontSize = `${baseFontSize.toFixed(2)}px`;
  } else {
    console.warn("Invalid base font size value");
  }
});

darkModeToggleElement.addEventListener("change", (event) => {
  const isDarkMode = event.target.checked;
  if (isDarkMode) {
    document.body.classList.add("dark");
  } else {
    document.body.classList.remove("dark");
  }
});

const fontFamilies = [
  { name: "ABeeZee", isLoaded: false },
  { name: "ADLaM Display", isLoaded: false },
  { name: "AR One Sans", isLoaded: false },
  { name: "Abel", isLoaded: false },
  { name: "Abhaya Libre", isLoaded: false },
  { name: "Aboreto", isLoaded: false },
  { name: "Abril Fatface", isLoaded: false },
  { name: "Abyssinica SIL", isLoaded: false },
  { name: "Aclonica", isLoaded: false },
  { name: "Acme", isLoaded: false },
  { name: "Actor", isLoaded: false },
  { name: "Adamina", isLoaded: false },
  { name: "Advent Pro", isLoaded: false },
  { name: "Agdasima", isLoaded: false },
  { name: "Aguafina Script", isLoaded: false },
  { name: "Akatab", isLoaded: false },
  { name: "Akaya Kanadaka", isLoaded: false },
  { name: "Akaya Telivigala", isLoaded: false },
  { name: "Akronim", isLoaded: false },
  { name: "Akshar", isLoaded: false },
  { name: "Aladin", isLoaded: false },
  { name: "Alata", isLoaded: false },
  { name: "Alatsi", isLoaded: false },
  { name: "Albert Sans", isLoaded: false },
  { name: "Aldrich", isLoaded: false },
  { name: "Alef", isLoaded: false },
  { name: "Alegreya", isLoaded: false },
  { name: "Alegreya SC", isLoaded: false },
  { name: "Alegreya Sans", isLoaded: false },
  { name: "Alegreya Sans SC", isLoaded: false },
  { name: "Aleo", isLoaded: false },
  { name: "Alex Brush", isLoaded: false },
  { name: "Alexandria", isLoaded: false },
  { name: "Alfa Slab One", isLoaded: false },
  { name: "Alice", isLoaded: false },
  { name: "Alike", isLoaded: false },
  { name: "Alike Angular", isLoaded: false },
  { name: "Alkalami", isLoaded: false },
  { name: "Alkatra", isLoaded: false },
  { name: "Allan", isLoaded: false },
  { name: "Allerta", isLoaded: false },
  { name: "Allerta Stencil", isLoaded: false },
  { name: "Allison", isLoaded: false },
  { name: "Allura", isLoaded: false },
  { name: "Almarai", isLoaded: false },
  { name: "Almendra", isLoaded: false },
  { name: "Almendra Display", isLoaded: false },
  { name: "Almendra SC", isLoaded: false },
  { name: "Alumni Sans", isLoaded: false },
  { name: "Alumni Sans Collegiate One", isLoaded: false },
  { name: "Alumni Sans Inline One", isLoaded: false },
  { name: "Alumni Sans Pinstripe", isLoaded: false },
  { name: "Amarante", isLoaded: false },
  { name: "Amaranth", isLoaded: false },
  { name: "Amatic SC", isLoaded: false },
  { name: "Amethysta", isLoaded: false },
  { name: "Amiko", isLoaded: false },
  { name: "Amiri", isLoaded: false },
  { name: "Amiri Quran", isLoaded: false },
  { name: "Amita", isLoaded: false },
  { name: "Anaheim", isLoaded: false },
  { name: "Andada Pro", isLoaded: false },
  { name: "Andika", isLoaded: false },
  { name: "Anek Bangla", isLoaded: false },
  { name: "Anek Devanagari", isLoaded: false },
  { name: "Anek Gujarati", isLoaded: false },
  { name: "Anek Gurmukhi", isLoaded: false },
  { name: "Anek Kannada", isLoaded: false },
  { name: "Anek Latin", isLoaded: false },
  { name: "Anek Malayalam", isLoaded: false },
  { name: "Anek Odia", isLoaded: false },
  { name: "Anek Tamil", isLoaded: false },
  { name: "Anek Telugu", isLoaded: false },
  { name: "Angkor", isLoaded: false },
  { name: "Annie Use Your Telescope", isLoaded: false },
  { name: "Anonymous Pro", isLoaded: false },
  { name: "Antic", isLoaded: false },
  { name: "Antic Didone", isLoaded: false },
  { name: "Antic Slab", isLoaded: false },
  { name: "Anton", isLoaded: false },
  { name: "Antonio", isLoaded: false },
  { name: "Anuphan", isLoaded: false },
  { name: "Anybody", isLoaded: false },
  { name: "Aoboshi One", isLoaded: false },
  { name: "Arapey", isLoaded: false },
  { name: "Arbutus", isLoaded: false },
  { name: "Arbutus Slab", isLoaded: false },
  { name: "Architects Daughter", isLoaded: false },
  { name: "Archivo", isLoaded: false },
  { name: "Archivo Black", isLoaded: false },
  { name: "Archivo Narrow", isLoaded: false },
  { name: "Are You Serious", isLoaded: false },
  { name: "Aref Ruqaa", isLoaded: false },
  { name: "Aref Ruqaa Ink", isLoaded: false },
  { name: "Arima", isLoaded: false },
  { name: "Arima Madurai", isLoaded: false },
  { name: "Arimo", isLoaded: false },
  { name: "Arizonia", isLoaded: false },
  { name: "Armata", isLoaded: false },
  { name: "Arsenal", isLoaded: false },
  { name: "Artifika", isLoaded: false },
  { name: "Arvo", isLoaded: false },
  { name: "Arya", isLoaded: false },
  { name: "Asap", isLoaded: false },
  { name: "Asap Condensed", isLoaded: false },
  { name: "Asar", isLoaded: false },
  { name: "Asset", isLoaded: false },
  { name: "Assistant", isLoaded: false },
  { name: "Astloch", isLoaded: false },
  { name: "Asul", isLoaded: false },
  { name: "Athiti", isLoaded: false },
  { name: "Atkinson Hyperlegible", isLoaded: false },
  { name: "Atkinson Hyperlegible Next", isLoaded: true },
  { name: "Atma", isLoaded: false },
  { name: "Atomic Age", isLoaded: false },
  { name: "Aubrey", isLoaded: false },
  { name: "Audiowide", isLoaded: false },
  { name: "Autour One", isLoaded: false },
  { name: "Average", isLoaded: false },
  { name: "Average Sans", isLoaded: false },
  { name: "Averia Gruesa Libre", isLoaded: false },
  { name: "Averia Libre", isLoaded: false },
  { name: "Averia Sans Libre", isLoaded: false },
  { name: "Averia Serif Libre", isLoaded: false },
  { name: "Azeret Mono", isLoaded: false },
  { name: "B612", isLoaded: false },
  { name: "B612 Mono", isLoaded: false },
  { name: "BIZ UDGothic", isLoaded: false },
  { name: "BIZ UDMincho", isLoaded: false },
  { name: "BIZ UDPGothic", isLoaded: false },
  { name: "BIZ UDPMincho", isLoaded: false },
  { name: "Babylonica", isLoaded: false },
  { name: "Bacasime Antique", isLoaded: false },
  { name: "Bad Script", isLoaded: false },
  { name: "Bagel Fat One", isLoaded: false },
  { name: "Bahiana", isLoaded: false },
  { name: "Bahianita", isLoaded: false },
  { name: "Bai Jamjuree", isLoaded: false },
  { name: "Bakbak One", isLoaded: false },
  { name: "Ballet", isLoaded: false },
  { name: "Baloo 2", isLoaded: false },
  { name: "Baloo Bhai 2", isLoaded: false },
  { name: "Baloo Bhaijaan 2", isLoaded: false },
  { name: "Baloo Bhaina 2", isLoaded: false },
  { name: "Baloo Chettan 2", isLoaded: false },
  { name: "Baloo Da 2", isLoaded: false },
  { name: "Baloo Paaji 2", isLoaded: false },
  { name: "Baloo Tamma 2", isLoaded: false },
  { name: "Baloo Tammudu 2", isLoaded: false },
  { name: "Baloo Thambi 2", isLoaded: false },
  { name: "Balsamiq Sans", isLoaded: false },
  { name: "Balthazar", isLoaded: false },
  { name: "Bangers", isLoaded: false },
  { name: "Barlow", isLoaded: false },
  { name: "Barlow Condensed", isLoaded: false },
  { name: "Barlow Semi Condensed", isLoaded: false },
  { name: "Barriecito", isLoaded: false },
  { name: "Barrio", isLoaded: false },
  { name: "Basic", isLoaded: false },
  { name: "Baskervville", isLoaded: false },
  { name: "Battambang", isLoaded: false },
  { name: "Baumans", isLoaded: false },
  { name: "Bayon", isLoaded: false },
  { name: "Be Vietnam Pro", isLoaded: false },
  { name: "Beau Rivage", isLoaded: false },
  { name: "Bebas Neue", isLoaded: false },
  { name: "Belanosima", isLoaded: false },
  { name: "Belgrano", isLoaded: false },
  { name: "Bellefair", isLoaded: false },
  { name: "Belleza", isLoaded: false },
  { name: "Bellota", isLoaded: false },
  { name: "Bellota Text", isLoaded: false },
  { name: "BenchNine", isLoaded: false },
  { name: "Benne", isLoaded: false },
  { name: "Bentham", isLoaded: false },
  { name: "Berkshire Swash", isLoaded: false },
  { name: "Besley", isLoaded: false },
  { name: "Beth Ellen", isLoaded: false },
  { name: "Bevan", isLoaded: false },
  { name: "BhuTuka Expanded One", isLoaded: false },
  { name: "Big Shoulders Display", isLoaded: false },
  { name: "Big Shoulders Inline Display", isLoaded: false },
  { name: "Big Shoulders Inline Text", isLoaded: false },
  { name: "Big Shoulders Stencil Display", isLoaded: false },
  { name: "Big Shoulders Stencil Text", isLoaded: false },
  { name: "Big Shoulders Text", isLoaded: false },
  { name: "Bigelow Rules", isLoaded: false },
  { name: "Bigshot One", isLoaded: false },
  { name: "Bilbo", isLoaded: false },
  { name: "Bilbo Swash Caps", isLoaded: false },
  { name: "BioRhyme", isLoaded: false },
  { name: "BioRhyme Expanded", isLoaded: false },
  { name: "Birthstone", isLoaded: false },
  { name: "Birthstone Bounce", isLoaded: false },
  { name: "Biryani", isLoaded: false },
  { name: "Bitter", isLoaded: false },
  { name: "Black And White Picture", isLoaded: false },
  { name: "Black Han Sans", isLoaded: false },
  { name: "Black Ops One", isLoaded: false },
  { name: "Blaka", isLoaded: false },
  { name: "Blaka Hollow", isLoaded: false },
  { name: "Blaka Ink", isLoaded: false },
  { name: "Blinker", isLoaded: false },
  { name: "Bodoni Moda", isLoaded: false },
  { name: "Bokor", isLoaded: false },
  { name: "Bona Nova", isLoaded: false },
  { name: "Bonbon", isLoaded: false },
  { name: "Bonheur Royale", isLoaded: false },
  { name: "Boogaloo", isLoaded: false },
  { name: "Borel", isLoaded: false },
  { name: "Bowlby One", isLoaded: false },
  { name: "Bowlby One SC", isLoaded: false },
  { name: "Braah One", isLoaded: false },
  { name: "Brawler", isLoaded: false },
  { name: "Bree Serif", isLoaded: false },
  { name: "Bricolage Grotesque", isLoaded: false },
  { name: "Bruno Ace", isLoaded: false },
  { name: "Bruno Ace SC", isLoaded: false },
  { name: "Brygada 1918", isLoaded: false },
  { name: "Bubblegum Sans", isLoaded: false },
  { name: "Bubbler One", isLoaded: false },
  { name: "Buda", isLoaded: false },
  { name: "Buenard", isLoaded: false },
  { name: "Bungee", isLoaded: false },
  { name: "Bungee Hairline", isLoaded: false },
  { name: "Bungee Inline", isLoaded: false },
  { name: "Bungee Outline", isLoaded: false },
  { name: "Bungee Shade", isLoaded: false },
  { name: "Bungee Spice", isLoaded: false },
  { name: "Butcherman", isLoaded: false },
  { name: "Butterfly Kids", isLoaded: false },
  { name: "Cabin", isLoaded: false },
  { name: "Cabin Condensed", isLoaded: false },
  { name: "Cabin Sketch", isLoaded: false },
  { name: "Caesar Dressing", isLoaded: false },
  { name: "Cagliostro", isLoaded: false },
  { name: "Cairo", isLoaded: false },
  { name: "Cairo Play", isLoaded: false },
  { name: "Caladea", isLoaded: false },
  { name: "Calistoga", isLoaded: false },
  { name: "Calligraffitti", isLoaded: false },
  { name: "Cambay", isLoaded: false },
  { name: "Cambo", isLoaded: false },
  { name: "Candal", isLoaded: false },
  { name: "Cantarell", isLoaded: false },
  { name: "Cantata One", isLoaded: false },
  { name: "Cantora One", isLoaded: false },
  { name: "Caprasimo", isLoaded: false },
  { name: "Capriola", isLoaded: false },
  { name: "Caramel", isLoaded: false },
  { name: "Carattere", isLoaded: false },
  { name: "Cardo", isLoaded: false },
  { name: "Carlito", isLoaded: false },
  { name: "Carme", isLoaded: false },
  { name: "Carrois Gothic", isLoaded: false },
  { name: "Carrois Gothic SC", isLoaded: false },
  { name: "Carter One", isLoaded: false },
  { name: "Castoro", isLoaded: false },
  { name: "Castoro Titling", isLoaded: false },
  { name: "Catamaran", isLoaded: false },
  { name: "Caudex", isLoaded: false },
  { name: "Caveat", isLoaded: false },
  { name: "Caveat Brush", isLoaded: false },
  { name: "Cedarville Cursive", isLoaded: false },
  { name: "Ceviche One", isLoaded: false },
  { name: "Chakra Petch", isLoaded: false },
  { name: "Changa", isLoaded: false },
  { name: "Changa One", isLoaded: false },
  { name: "Chango", isLoaded: false },
  { name: "Charis SIL", isLoaded: false },
  { name: "Charm", isLoaded: false },
  { name: "Charmonman", isLoaded: false },
  { name: "Chathura", isLoaded: false },
  { name: "Chau Philomene One", isLoaded: false },
  { name: "Chela One", isLoaded: false },
  { name: "Chelsea Market", isLoaded: false },
  { name: "Chenla", isLoaded: false },
  { name: "Cherish", isLoaded: false },
  { name: "Cherry Bomb One", isLoaded: false },
  { name: "Cherry Cream Soda", isLoaded: false },
  { name: "Cherry Swash", isLoaded: false },
  { name: "Chewy", isLoaded: false },
  { name: "Chicle", isLoaded: false },
  { name: "Chilanka", isLoaded: false },
  { name: "Chivo", isLoaded: false },
  { name: "Chivo Mono", isLoaded: false },
  { name: "Chokokutai", isLoaded: false },
  { name: "Chonburi", isLoaded: false },
  { name: "Cinzel", isLoaded: false },
  { name: "Cinzel Decorative", isLoaded: false },
  { name: "Clicker Script", isLoaded: false },
  { name: "Climate Crisis", isLoaded: false },
  { name: "Coda", isLoaded: false },
  { name: "Coda Caption", isLoaded: false },
  { name: "Codystar", isLoaded: false },
  { name: "Coiny", isLoaded: false },
  { name: "Combo", isLoaded: false },
  { name: "Comfortaa", isLoaded: false },
  { name: "Comforter", isLoaded: false },
  { name: "Comforter Brush", isLoaded: false },
  { name: "Comic Neue", isLoaded: false },
  { name: "Coming Soon", isLoaded: false },
  { name: "Comme", isLoaded: false },
  { name: "Commissioner", isLoaded: false },
  { name: "Concert One", isLoaded: false },
  { name: "Condiment", isLoaded: false },
  { name: "Content", isLoaded: false },
  { name: "Contrail One", isLoaded: false },
  { name: "Convergence", isLoaded: false },
  { name: "Cookie", isLoaded: false },
  { name: "Copse", isLoaded: false },
  { name: "Corben", isLoaded: false },
  { name: "Corinthia", isLoaded: false },
  { name: "Cormorant", isLoaded: false },
  { name: "Cormorant Garamond", isLoaded: false },
  { name: "Cormorant Infant", isLoaded: false },
  { name: "Cormorant SC", isLoaded: false },
  { name: "Cormorant Unicase", isLoaded: false },
  { name: "Cormorant Upright", isLoaded: false },
  { name: "Courgette", isLoaded: false },
  { name: "Courier Prime", isLoaded: false },
  { name: "Cousine", isLoaded: false },
  { name: "Coustard", isLoaded: false },
  { name: "Covered By Your Grace", isLoaded: false },
  { name: "Crafty Girls", isLoaded: false },
  { name: "Creepster", isLoaded: false },
  { name: "Crete Round", isLoaded: false },
  { name: "Crimson Pro", isLoaded: false },
  { name: "Crimson Text", isLoaded: false },
  { name: "Croissant One", isLoaded: false },
  { name: "Crushed", isLoaded: false },
  { name: "Cuprum", isLoaded: false },
  { name: "Cute Font", isLoaded: false },
  { name: "Cutive", isLoaded: false },
  { name: "Cutive Mono", isLoaded: false },
  { name: "DM Mono", isLoaded: false },
  { name: "DM Sans", isLoaded: false },
  { name: "DM Serif Display", isLoaded: false },
  { name: "DM Serif Text", isLoaded: false },
  { name: "Dai Banna SIL", isLoaded: false },
  { name: "Damion", isLoaded: false },
  { name: "Dancing Script", isLoaded: false },
  { name: "Dangrek", isLoaded: false },
  { name: "Darker Grotesque", isLoaded: false },
  { name: "Darumadrop One", isLoaded: false },
  { name: "David Libre", isLoaded: false },
  { name: "Dawning of a New Day", isLoaded: false },
  { name: "Days One", isLoaded: false },
  { name: "Dekko", isLoaded: false },
  { name: "Dela Gothic One", isLoaded: false },
  { name: "Delicious Handrawn", isLoaded: false },
  { name: "Delius", isLoaded: false },
  { name: "Delius Swash Caps", isLoaded: false },
  { name: "Delius Unicase", isLoaded: false },
  { name: "Della Respira", isLoaded: false },
  { name: "Denk One", isLoaded: false },
  { name: "Devonshire", isLoaded: false },
  { name: "Dhurjati", isLoaded: false },
  { name: "Didact Gothic", isLoaded: false },
  { name: "Diphylleia", isLoaded: false },
  { name: "Diplomata", isLoaded: false },
  { name: "Diplomata SC", isLoaded: false },
  { name: "Do Hyeon", isLoaded: false },
  { name: "Dokdo", isLoaded: false },
  { name: "Domine", isLoaded: false },
  { name: "Donegal One", isLoaded: false },
  { name: "Dongle", isLoaded: false },
  { name: "Doppio One", isLoaded: false },
  { name: "Dorsa", isLoaded: false },
  { name: "Dosis", isLoaded: false },
  { name: "DotGothic16", isLoaded: false },
  { name: "Dr Sugiyama", isLoaded: false },
  { name: "Duru Sans", isLoaded: false },
  { name: "DynaPuff", isLoaded: false },
  { name: "Dynalight", isLoaded: false },
  { name: "EB Garamond", isLoaded: false },
  { name: "Eagle Lake", isLoaded: false },
  { name: "East Sea Dokdo", isLoaded: false },
  { name: "Eater", isLoaded: false },
  { name: "Economica", isLoaded: false },
  { name: "Eczar", isLoaded: false },
  { name: "Edu NSW ACT Foundation", isLoaded: false },
  { name: "Edu QLD Beginner", isLoaded: false },
  { name: "Edu SA Beginner", isLoaded: false },
  { name: "Edu TAS Beginner", isLoaded: false },
  { name: "Edu VIC WA NT Beginner", isLoaded: false },
  { name: "El Messiri", isLoaded: false },
  { name: "Electrolize", isLoaded: false },
  { name: "Elsie", isLoaded: false },
  { name: "Elsie Swash Caps", isLoaded: false },
  { name: "Emblema One", isLoaded: false },
  { name: "Emilys Candy", isLoaded: false },
  { name: "Encode Sans", isLoaded: false },
  { name: "Encode Sans Condensed", isLoaded: false },
  { name: "Encode Sans Expanded", isLoaded: false },
  { name: "Encode Sans SC", isLoaded: false },
  { name: "Encode Sans Semi Condensed", isLoaded: false },
  { name: "Encode Sans Semi Expanded", isLoaded: false },
  { name: "Engagement", isLoaded: false },
  { name: "Englebert", isLoaded: false },
  { name: "Enriqueta", isLoaded: false },
  { name: "Ephesis", isLoaded: false },
  { name: "Epilogue", isLoaded: false },
  { name: "Erica One", isLoaded: false },
  { name: "Esteban", isLoaded: false },
  { name: "Estonia", isLoaded: false },
  { name: "Euphoria Script", isLoaded: false },
  { name: "Ewert", isLoaded: false },
  { name: "Exo", isLoaded: false },
  { name: "Exo 2", isLoaded: false },
  { name: "Expletus Sans", isLoaded: false },
  { name: "Explora", isLoaded: false },
  { name: "Fahkwang", isLoaded: false },
  { name: "Familjen Grotesk", isLoaded: false },
  { name: "Fanwood Text", isLoaded: false },
  { name: "Farro", isLoaded: false },
  { name: "Farsan", isLoaded: false },
  { name: "Fascinate", isLoaded: false },
  { name: "Fascinate Inline", isLoaded: false },
  { name: "Faster One", isLoaded: false },
  { name: "Fasthand", isLoaded: false },
  { name: "Fauna One", isLoaded: false },
  { name: "Faustina", isLoaded: false },
  { name: "Federant", isLoaded: false },
  { name: "Federo", isLoaded: false },
  { name: "Felipa", isLoaded: false },
  { name: "Fenix", isLoaded: false },
  { name: "Festive", isLoaded: false },
  { name: "Figtree", isLoaded: false },
  { name: "Finger Paint", isLoaded: false },
  { name: "Finlandica", isLoaded: false },
  { name: "Fira Code", isLoaded: false },
  { name: "Fira Mono", isLoaded: false },
  { name: "Fira Sans", isLoaded: false },
  { name: "Fira Sans Condensed", isLoaded: false },
  { name: "Fira Sans Extra Condensed", isLoaded: false },
  { name: "Fjalla One", isLoaded: false },
  { name: "Fjord One", isLoaded: false },
  { name: "Flamenco", isLoaded: false },
  { name: "Flavors", isLoaded: false },
  { name: "Fleur De Leah", isLoaded: false },
  { name: "Flow Block", isLoaded: false },
  { name: "Flow Circular", isLoaded: false },
  { name: "Flow Rounded", isLoaded: false },
  { name: "Foldit", isLoaded: false },
  { name: "Fondamento", isLoaded: false },
  { name: "Fontdiner Swanky", isLoaded: false },
  { name: "Forum", isLoaded: false },
  { name: "Fragment Mono", isLoaded: false },
  { name: "Francois One", isLoaded: false },
  { name: "Frank Ruhl Libre", isLoaded: false },
  { name: "Fraunces", isLoaded: false },
  { name: "Freckle Face", isLoaded: false },
  { name: "Fredericka the Great", isLoaded: false },
  { name: "Fredoka", isLoaded: false },
  { name: "Freehand", isLoaded: false },
  { name: "Fresca", isLoaded: false },
  { name: "Frijole", isLoaded: false },
  { name: "Fruktur", isLoaded: false },
  { name: "Fugaz One", isLoaded: false },
  { name: "Fuggles", isLoaded: false },
  { name: "Fuzzy Bubbles", isLoaded: false },
  { name: "GFS Didot", isLoaded: false },
  { name: "GFS Neohellenic", isLoaded: false },
  { name: "Gabarito", isLoaded: false },
  { name: "Gabriela", isLoaded: false },
  { name: "Gaegu", isLoaded: false },
  { name: "Gafata", isLoaded: false },
  { name: "Gajraj One", isLoaded: false },
  { name: "Galada", isLoaded: false },
  { name: "Galdeano", isLoaded: false },
  { name: "Galindo", isLoaded: false },
  { name: "Gamja Flower", isLoaded: false },
  { name: "Gantari", isLoaded: false },
  { name: "Gasoek One", isLoaded: false },
  { name: "Gayathri", isLoaded: false },
  { name: "Gelasio", isLoaded: false },
  { name: "Gemunu Libre", isLoaded: false },
  { name: "Genos", isLoaded: false },
  { name: "Gentium Book Plus", isLoaded: false },
  { name: "Gentium Plus", isLoaded: false },
  { name: "Geo", isLoaded: false },
  { name: "Geologica", isLoaded: false },
  { name: "Georama", isLoaded: false },
  { name: "Geostar", isLoaded: false },
  { name: "Geostar Fill", isLoaded: false },
  { name: "Germania One", isLoaded: false },
  { name: "Gideon Roman", isLoaded: false },
  { name: "Gidugu", isLoaded: false },
  { name: "Gilda Display", isLoaded: false },
  { name: "Girassol", isLoaded: false },
  { name: "Give You Glory", isLoaded: false },
  { name: "Glass Antiqua", isLoaded: false },
  { name: "Glegoo", isLoaded: false },
  { name: "Gloock", isLoaded: false },
  { name: "Gloria Hallelujah", isLoaded: false },
  { name: "Glory", isLoaded: false },
  { name: "Gluten", isLoaded: false },
  { name: "Goblin One", isLoaded: false },
  { name: "Gochi Hand", isLoaded: false },
  { name: "Goldman", isLoaded: false },
  { name: "Golos Text", isLoaded: false },
  { name: "Gorditas", isLoaded: false },
  { name: "Gothic A1", isLoaded: false },
  { name: "Gotu", isLoaded: false },
  { name: "Goudy Bookletter 1911", isLoaded: false },
  { name: "Gowun Batang", isLoaded: false },
  { name: "Gowun Dodum", isLoaded: false },
  { name: "Graduate", isLoaded: false },
  { name: "Grand Hotel", isLoaded: false },
  { name: "Grandiflora One", isLoaded: false },
  { name: "Grandstander", isLoaded: false },
  { name: "Grape Nuts", isLoaded: false },
  { name: "Gravitas One", isLoaded: false },
  { name: "Great Vibes", isLoaded: false },
  { name: "Grechen Fuemen", isLoaded: false },
  { name: "Grenze", isLoaded: false },
  { name: "Grenze Gotisch", isLoaded: false },
  { name: "Grey Qo", isLoaded: false },
  { name: "Griffy", isLoaded: false },
  { name: "Gruppo", isLoaded: false },
  { name: "Gudea", isLoaded: false },
  { name: "Gugi", isLoaded: false },
  { name: "Gulzar", isLoaded: false },
  { name: "Gupter", isLoaded: false },
  { name: "Gurajada", isLoaded: false },
  { name: "Gwendolyn", isLoaded: false },
  { name: "Habibi", isLoaded: false },
  { name: "Hachi Maru Pop", isLoaded: false },
  { name: "Hahmlet", isLoaded: false },
  { name: "Halant", isLoaded: false },
  { name: "Hammersmith One", isLoaded: false },
  { name: "Hanalei", isLoaded: false },
  { name: "Hanalei Fill", isLoaded: false },
  { name: "Handjet", isLoaded: false },
  { name: "Handlee", isLoaded: false },
  { name: "Hanken Grotesk", isLoaded: false },
  { name: "Hanuman", isLoaded: false },
  { name: "Happy Monkey", isLoaded: false },
  { name: "Harmattan", isLoaded: false },
  { name: "Headland One", isLoaded: false },
  { name: "Heebo", isLoaded: false },
  { name: "Henny Penny", isLoaded: false },
  { name: "Hepta Slab", isLoaded: false },
  { name: "Herr Von Muellerhoff", isLoaded: false },
  { name: "Hi Melody", isLoaded: false },
  { name: "Hina Mincho", isLoaded: false },
  { name: "Hind", isLoaded: false },
  { name: "Hind Guntur", isLoaded: false },
  { name: "Hind Madurai", isLoaded: false },
  { name: "Hind Siliguri", isLoaded: false },
  { name: "Hind Vadodara", isLoaded: false },
  { name: "Holtwood One SC", isLoaded: false },
  { name: "Homemade Apple", isLoaded: false },
  { name: "Homenaje", isLoaded: false },
  { name: "Hubballi", isLoaded: false },
  { name: "Hurricane", isLoaded: false },
  { name: "IBM Plex Mono", isLoaded: false },
  { name: "IBM Plex Sans", isLoaded: false },
  { name: "IBM Plex Sans Arabic", isLoaded: false },
  { name: "IBM Plex Sans Condensed", isLoaded: false },
  { name: "IBM Plex Sans Devanagari", isLoaded: false },
  { name: "IBM Plex Sans Hebrew", isLoaded: false },
  { name: "IBM Plex Sans JP", isLoaded: false },
  { name: "IBM Plex Sans KR", isLoaded: false },
  { name: "IBM Plex Sans Thai", isLoaded: false },
  { name: "IBM Plex Sans Thai Looped", isLoaded: false },
  { name: "IBM Plex Serif", isLoaded: false },
  { name: "IM Fell DW Pica", isLoaded: false },
  { name: "IM Fell DW Pica SC", isLoaded: false },
  { name: "IM Fell Double Pica", isLoaded: false },
  { name: "IM Fell Double Pica SC", isLoaded: false },
  { name: "IM Fell English", isLoaded: false },
  { name: "IM Fell English SC", isLoaded: false },
  { name: "IM Fell French Canon", isLoaded: false },
  { name: "IM Fell French Canon SC", isLoaded: false },
  { name: "IM Fell Great Primer", isLoaded: false },
  { name: "IM Fell Great Primer SC", isLoaded: false },
  { name: "Ibarra Real Nova", isLoaded: false },
  { name: "Iceberg", isLoaded: false },
  { name: "Iceland", isLoaded: false },
  { name: "Imbue", isLoaded: false },
  { name: "Imperial Script", isLoaded: false },
  { name: "Imprima", isLoaded: false },
  { name: "Inclusive Sans", isLoaded: false },
  { name: "Inconsolata", isLoaded: false },
  { name: "Inder", isLoaded: false },
  { name: "Indie Flower", isLoaded: false },
  { name: "Ingrid Darling", isLoaded: false },
  { name: "Inika", isLoaded: false },
  { name: "Inknut Antiqua", isLoaded: false },
  { name: "Inria Sans", isLoaded: false },
  { name: "Inria Serif", isLoaded: false },
  { name: "Inspiration", isLoaded: false },
  { name: "Instrument Sans", isLoaded: false },
  { name: "Instrument Serif", isLoaded: false },
  { name: "Inter", isLoaded: false },
  { name: "Inter Tight", isLoaded: false },
  { name: "Irish Grover", isLoaded: false },
  { name: "Island Moments", isLoaded: false },
  { name: "Istok Web", isLoaded: false },
  { name: "Italiana", isLoaded: false },
  { name: "Italianno", isLoaded: false },
  { name: "Itim", isLoaded: false },
  { name: "Jacques Francois", isLoaded: false },
  { name: "Jacques Francois Shadow", isLoaded: false },
  { name: "Jaldi", isLoaded: false },
  { name: "JetBrains Mono", isLoaded: false },
  { name: "Jim Nightshade", isLoaded: false },
  { name: "Joan", isLoaded: false },
  { name: "Jockey One", isLoaded: false },
  { name: "Jolly Lodger", isLoaded: false },
  { name: "Jomhuria", isLoaded: false },
  { name: "Jomolhari", isLoaded: false },
  { name: "Josefin Sans", isLoaded: false },
  { name: "Josefin Slab", isLoaded: false },
  { name: "Jost", isLoaded: false },
  { name: "Joti One", isLoaded: false },
  { name: "Jua", isLoaded: false },
  { name: "Judson", isLoaded: false },
  { name: "Julee", isLoaded: false },
  { name: "Julius Sans One", isLoaded: false },
  { name: "Junge", isLoaded: false },
  { name: "Jura", isLoaded: false },
  { name: "Just Another Hand", isLoaded: false },
  { name: "Just Me Again Down Here", isLoaded: false },
  { name: "K2D", isLoaded: false },
  { name: "Kablammo", isLoaded: false },
  { name: "Kadwa", isLoaded: false },
  { name: "Kaisei Decol", isLoaded: false },
  { name: "Kaisei HarunoUmi", isLoaded: false },
  { name: "Kaisei Opti", isLoaded: false },
  { name: "Kaisei Tokumin", isLoaded: false },
  { name: "Kalam", isLoaded: false },
  { name: "Kameron", isLoaded: false },
  { name: "Kanit", isLoaded: false },
  { name: "Kantumruy Pro", isLoaded: false },
  { name: "Karantina", isLoaded: false },
  { name: "Karla", isLoaded: false },
  { name: "Karma", isLoaded: false },
  { name: "Katibeh", isLoaded: false },
  { name: "Kaushan Script", isLoaded: false },
  { name: "Kavivanar", isLoaded: false },
  { name: "Kavoon", isLoaded: false },
  { name: "Kdam Thmor Pro", isLoaded: false },
  { name: "Keania One", isLoaded: false },
  { name: "Kelly Slab", isLoaded: false },
  { name: "Kenia", isLoaded: false },
  { name: "Khand", isLoaded: false },
  { name: "Khmer", isLoaded: false },
  { name: "Khula", isLoaded: false },
  { name: "Kings", isLoaded: false },
  { name: "Kirang Haerang", isLoaded: false },
  { name: "Kite One", isLoaded: false },
  { name: "Kiwi Maru", isLoaded: false },
  { name: "Klee One", isLoaded: false },
  { name: "Knewave", isLoaded: false },
  { name: "KoHo", isLoaded: false },
  { name: "Kodchasan", isLoaded: false },
  { name: "Koh Santepheap", isLoaded: false },
  { name: "Kolker Brush", isLoaded: false },
  { name: "Konkhmer Sleokchher", isLoaded: false },
  { name: "Kosugi", isLoaded: false },
  { name: "Kosugi Maru", isLoaded: false },
  { name: "Kotta One", isLoaded: false },
  { name: "Koulen", isLoaded: false },
  { name: "Kranky", isLoaded: false },
  { name: "Kreon", isLoaded: false },
  { name: "Kristi", isLoaded: false },
  { name: "Krona One", isLoaded: false },
  { name: "Krub", isLoaded: false },
  { name: "Kufam", isLoaded: false },
  { name: "Kulim Park", isLoaded: false },
  { name: "Kumar One", isLoaded: false },
  { name: "Kumar One Outline", isLoaded: false },
  { name: "Kumbh Sans", isLoaded: false },
  { name: "Kurale", isLoaded: false },
  { name: "La Belle Aurore", isLoaded: false },
  { name: "Labrada", isLoaded: false },
  { name: "Lacquer", isLoaded: false },
  { name: "Laila", isLoaded: false },
  { name: "Lakki Reddy", isLoaded: false },
  { name: "Lalezar", isLoaded: false },
  { name: "Lancelot", isLoaded: false },
  { name: "Langar", isLoaded: false },
  { name: "Lateef", isLoaded: false },
  { name: "Lato", isLoaded: false },
  { name: "Lavishly Yours", isLoaded: false },
  { name: "League Gothic", isLoaded: false },
  { name: "League Script", isLoaded: false },
  { name: "League Spartan", isLoaded: false },
  { name: "Leckerli One", isLoaded: false },
  { name: "Ledger", isLoaded: false },
  { name: "Lekton", isLoaded: false },
  { name: "Lemon", isLoaded: false },
  { name: "Lemonada", isLoaded: false },
  { name: "Lexend", isLoaded: false },
  { name: "Lexend Deca", isLoaded: false },
  { name: "Lexend Exa", isLoaded: false },
  { name: "Lexend Giga", isLoaded: false },
  { name: "Lexend Mega", isLoaded: false },
  { name: "Lexend Peta", isLoaded: false },
  { name: "Lexend Tera", isLoaded: false },
  { name: "Lexend Zetta", isLoaded: false },
  { name: "Libre Barcode 128", isLoaded: false },
  { name: "Libre Barcode 128 Text", isLoaded: false },
  { name: "Libre Barcode 39", isLoaded: false },
  { name: "Libre Barcode 39 Extended", isLoaded: false },
  { name: "Libre Barcode 39 Extended Text", isLoaded: false },
  { name: "Libre Barcode 39 Text", isLoaded: false },
  { name: "Libre Barcode EAN13 Text", isLoaded: false },
  { name: "Libre Baskerville", isLoaded: false },
  { name: "Libre Bodoni", isLoaded: false },
  { name: "Libre Caslon Display", isLoaded: false },
  { name: "Libre Caslon Text", isLoaded: false },
  { name: "Libre Franklin", isLoaded: false },
  { name: "Licorice", isLoaded: false },
  { name: "Life Savers", isLoaded: false },
  { name: "Lilita One", isLoaded: false },
  { name: "Lily Script One", isLoaded: false },
  { name: "Limelight", isLoaded: false },
  { name: "Linden Hill", isLoaded: false },
  { name: "Lisu Bosa", isLoaded: false },
  { name: "Literata", isLoaded: false },
  { name: "Liu Jian Mao Cao", isLoaded: false },
  { name: "Livvic", isLoaded: false },
  { name: "Lobster", isLoaded: false },
  { name: "Lobster Two", isLoaded: false },
  { name: "Londrina Outline", isLoaded: false },
  { name: "Londrina Shadow", isLoaded: false },
  { name: "Londrina Sketch", isLoaded: false },
  { name: "Londrina Solid", isLoaded: false },
  { name: "Long Cang", isLoaded: false },
  { name: "Lora", isLoaded: false },
  { name: "Love Light", isLoaded: false },
  { name: "Love Ya Like A Sister", isLoaded: false },
  { name: "Loved by the King", isLoaded: false },
  { name: "Lovers Quarrel", isLoaded: false },
  { name: "Luckiest Guy", isLoaded: false },
  { name: "Lugrasimo", isLoaded: false },
  { name: "Lumanosimo", isLoaded: false },
  { name: "Lunasima", isLoaded: false },
  { name: "Lusitana", isLoaded: false },
  { name: "Lustria", isLoaded: false },
  { name: "Luxurious Roman", isLoaded: false },
  { name: "Luxurious Script", isLoaded: false },
  { name: "M PLUS 1", isLoaded: false },
  { name: "M PLUS 1 Code", isLoaded: false },
  { name: "M PLUS 1p", isLoaded: false },
  { name: "M PLUS 2", isLoaded: false },
  { name: "M PLUS Code Latin", isLoaded: false },
  { name: "M PLUS Rounded 1c", isLoaded: false },
  { name: "Ma Shan Zheng", isLoaded: false },
  { name: "Macondo", isLoaded: false },
  { name: "Macondo Swash Caps", isLoaded: false },
  { name: "Mada", isLoaded: false },
  { name: "Magra", isLoaded: false },
  { name: "Maiden Orange", isLoaded: false },
  { name: "Maitree", isLoaded: false },
  { name: "Major Mono Display", isLoaded: false },
  { name: "Mako", isLoaded: false },
  { name: "Mali", isLoaded: false },
  { name: "Mallanna", isLoaded: false },
  { name: "Mandali", isLoaded: false },
  { name: "Manjari", isLoaded: false },
  { name: "Manrope", isLoaded: false },
  { name: "Mansalva", isLoaded: false },
  { name: "Manuale", isLoaded: false },
  { name: "Marcellus", isLoaded: false },
  { name: "Marcellus SC", isLoaded: false },
  { name: "Marck Script", isLoaded: false },
  { name: "Margarine", isLoaded: false },
  { name: "Marhey", isLoaded: false },
  { name: "Markazi Text", isLoaded: false },
  { name: "Marko One", isLoaded: false },
  { name: "Marmelad", isLoaded: false },
  { name: "Martel", isLoaded: false },
  { name: "Martel Sans", isLoaded: false },
  { name: "Martian Mono", isLoaded: false },
  { name: "Marvel", isLoaded: false },
  { name: "Mate", isLoaded: false },
  { name: "Mate SC", isLoaded: false },
  { name: "Material Icons", isLoaded: false },
  { name: "Material Icons Outlined", isLoaded: false },
  { name: "Material Icons Round", isLoaded: false },
  { name: "Material Icons Sharp", isLoaded: false },
  { name: "Material Icons Two Tone", isLoaded: false },
  { name: "Material Symbols Outlined", isLoaded: false },
  { name: "Material Symbols Rounded", isLoaded: false },
  { name: "Material Symbols Sharp", isLoaded: false },
  { name: "Maven Pro", isLoaded: false },
  { name: "McLaren", isLoaded: false },
  { name: "Mea Culpa", isLoaded: false },
  { name: "Meddon", isLoaded: false },
  { name: "MedievalSharp", isLoaded: false },
  { name: "Medula One", isLoaded: false },
  { name: "Meera Inimai", isLoaded: false },
  { name: "Megrim", isLoaded: false },
  { name: "Meie Script", isLoaded: false },
  { name: "Meow Script", isLoaded: false },
  { name: "Merienda", isLoaded: false },
  { name: "Merriweather", isLoaded: false },
  { name: "Merriweather Sans", isLoaded: false },
  { name: "Metal", isLoaded: false },
  { name: "Metal Mania", isLoaded: false },
  { name: "Metamorphous", isLoaded: false },
  { name: "Metrophobic", isLoaded: false },
  { name: "Michroma", isLoaded: false },
  { name: "Milonga", isLoaded: false },
  { name: "Miltonian", isLoaded: false },
  { name: "Miltonian Tattoo", isLoaded: false },
  { name: "Mina", isLoaded: false },
  { name: "Mingzat", isLoaded: false },
  { name: "Miniver", isLoaded: false },
  { name: "Miriam Libre", isLoaded: false },
  { name: "Mirza", isLoaded: false },
  { name: "Miss Fajardose", isLoaded: false },
  { name: "Mitr", isLoaded: false },
  { name: "Mochiy Pop One", isLoaded: false },
  { name: "Mochiy Pop P One", isLoaded: false },
  { name: "Modak", isLoaded: false },
  { name: "Modern Antiqua", isLoaded: false },
  { name: "Mogra", isLoaded: false },
  { name: "Mohave", isLoaded: false },
  { name: "Moirai One", isLoaded: false },
  { name: "Molengo", isLoaded: false },
  { name: "Molle", isLoaded: false },
  { name: "Monda", isLoaded: false },
  { name: "Monofett", isLoaded: false },
  { name: "Monomaniac One", isLoaded: false },
  { name: "Monoton", isLoaded: false },
  { name: "Monsieur La Doulaise", isLoaded: false },
  { name: "Montaga", isLoaded: false },
  { name: "Montagu Slab", isLoaded: false },
  { name: "MonteCarlo", isLoaded: false },
  { name: "Montez", isLoaded: false },
  { name: "Montserrat", isLoaded: false },
  { name: "Montserrat Alternates", isLoaded: false },
  { name: "Montserrat Subrayada", isLoaded: false },
  { name: "Moo Lah Lah", isLoaded: false },
  { name: "Mooli", isLoaded: false },
  { name: "Moon Dance", isLoaded: false },
  { name: "Moul", isLoaded: false },
  { name: "Moulpali", isLoaded: false },
  { name: "Mountains of Christmas", isLoaded: false },
  { name: "Mouse Memoirs", isLoaded: false },
  { name: "Mr Bedfort", isLoaded: false },
  { name: "Mr Dafoe", isLoaded: false },
  { name: "Mr De Haviland", isLoaded: false },
  { name: "Mrs Saint Delafield", isLoaded: false },
  { name: "Mrs Sheppards", isLoaded: false },
  { name: "Ms Madi", isLoaded: false },
  { name: "Mukta", isLoaded: false },
  { name: "Mukta Mahee", isLoaded: false },
  { name: "Mukta Malar", isLoaded: false },
  { name: "Mukta Vaani", isLoaded: false },
  { name: "Mulish", isLoaded: false },
  { name: "Murecho", isLoaded: false },
  { name: "MuseoModerno", isLoaded: false },
  { name: "My Soul", isLoaded: false },
  { name: "Mynerve", isLoaded: false },
  { name: "Mystery Quest", isLoaded: false },
  { name: "NTR", isLoaded: false },
  { name: "Nabla", isLoaded: false },
  { name: "Nanum Brush Script", isLoaded: false },
  { name: "Nanum Gothic", isLoaded: false },
  { name: "Nanum Gothic Coding", isLoaded: false },
  { name: "Nanum Myeongjo", isLoaded: false },
  { name: "Nanum Pen Script", isLoaded: false },
  { name: "Narnoor", isLoaded: false },
  { name: "Neonderthaw", isLoaded: false },
  { name: "Nerko One", isLoaded: false },
  { name: "Neucha", isLoaded: false },
  { name: "Neuton", isLoaded: false },
  { name: "New Rocker", isLoaded: false },
  { name: "New Tegomin", isLoaded: false },
  { name: "News Cycle", isLoaded: false },
  { name: "Newsreader", isLoaded: false },
  { name: "Niconne", isLoaded: false },
  { name: "Niramit", isLoaded: false },
  { name: "Nixie One", isLoaded: false },
  { name: "Nobile", isLoaded: false },
  { name: "Nokora", isLoaded: false },
  { name: "Norican", isLoaded: false },
  { name: "Nosifer", isLoaded: false },
  { name: "Notable", isLoaded: false },
  { name: "Nothing You Could Do", isLoaded: false },
  { name: "Noticia Text", isLoaded: false },
  { name: "Noto Color Emoji", isLoaded: false },
  { name: "Noto Emoji", isLoaded: false },
  { name: "Noto Kufi Arabic", isLoaded: false },
  { name: "Noto Music", isLoaded: false },
  { name: "Noto Naskh Arabic", isLoaded: false },
  { name: "Noto Nastaliq Urdu", isLoaded: false },
  { name: "Noto Rashi Hebrew", isLoaded: false },
  { name: "Noto Sans", isLoaded: false },
  { name: "Noto Sans Adlam", isLoaded: false },
  { name: "Noto Sans Adlam Unjoined", isLoaded: false },
  { name: "Noto Sans Anatolian Hieroglyphs", isLoaded: false },
  { name: "Noto Sans Arabic", isLoaded: false },
  { name: "Noto Sans Armenian", isLoaded: false },
  { name: "Noto Sans Avestan", isLoaded: false },
  { name: "Noto Sans Balinese", isLoaded: false },
  { name: "Noto Sans Bamum", isLoaded: false },
  { name: "Noto Sans Bassa Vah", isLoaded: false },
  { name: "Noto Sans Batak", isLoaded: false },
  { name: "Noto Sans Bengali", isLoaded: false },
  { name: "Noto Sans Bhaiksuki", isLoaded: false },
  { name: "Noto Sans Brahmi", isLoaded: false },
  { name: "Noto Sans Buginese", isLoaded: false },
  { name: "Noto Sans Buhid", isLoaded: false },
  { name: "Noto Sans Canadian Aboriginal", isLoaded: false },
  { name: "Noto Sans Carian", isLoaded: false },
  { name: "Noto Sans Caucasian Albanian", isLoaded: false },
  { name: "Noto Sans Chakma", isLoaded: false },
  { name: "Noto Sans Cham", isLoaded: false },
  { name: "Noto Sans Cherokee", isLoaded: false },
  { name: "Noto Sans Chorasmian", isLoaded: false },
  { name: "Noto Sans Coptic", isLoaded: false },
  { name: "Noto Sans Cuneiform", isLoaded: false },
  { name: "Noto Sans Cypriot", isLoaded: false },
  { name: "Noto Sans Cypro Minoan", isLoaded: false },
  { name: "Noto Sans Deseret", isLoaded: false },
  { name: "Noto Sans Devanagari", isLoaded: false },
  { name: "Noto Sans Display", isLoaded: false },
  { name: "Noto Sans Duployan", isLoaded: false },
  { name: "Noto Sans Egyptian Hieroglyphs", isLoaded: false },
  { name: "Noto Sans Elbasan", isLoaded: false },
  { name: "Noto Sans Elymaic", isLoaded: false },
  { name: "Noto Sans Ethiopic", isLoaded: false },
  { name: "Noto Sans Georgian", isLoaded: false },
  { name: "Noto Sans Glagolitic", isLoaded: false },
  { name: "Noto Sans Gothic", isLoaded: false },
  { name: "Noto Sans Grantha", isLoaded: false },
  { name: "Noto Sans Gujarati", isLoaded: false },
  { name: "Noto Sans Gunjala Gondi", isLoaded: false },
  { name: "Noto Sans Gurmukhi", isLoaded: false },
  { name: "Noto Sans HK", isLoaded: false },
  { name: "Noto Sans Hanifi Rohingya", isLoaded: false },
  { name: "Noto Sans Hanunoo", isLoaded: false },
  { name: "Noto Sans Hatran", isLoaded: false },
  { name: "Noto Sans Hebrew", isLoaded: false },
  { name: "Noto Sans Imperial Aramaic", isLoaded: false },
  { name: "Noto Sans Indic Siyaq Numbers", isLoaded: false },
  { name: "Noto Sans Inscriptional Pahlavi", isLoaded: false },
  { name: "Noto Sans Inscriptional Parthian", isLoaded: false },
  { name: "Noto Sans JP", isLoaded: false },
  { name: "Noto Sans Javanese", isLoaded: false },
  { name: "Noto Sans KR", isLoaded: false },
  { name: "Noto Sans Kaithi", isLoaded: false },
  { name: "Noto Sans Kannada", isLoaded: false },
  { name: "Noto Sans Kayah Li", isLoaded: false },
  { name: "Noto Sans Kharoshthi", isLoaded: false },
  { name: "Noto Sans Khmer", isLoaded: false },
  { name: "Noto Sans Khojki", isLoaded: false },
  { name: "Noto Sans Khudawadi", isLoaded: false },
  { name: "Noto Sans Lao", isLoaded: false },
  { name: "Noto Sans Lao Looped", isLoaded: false },
  { name: "Noto Sans Lepcha", isLoaded: false },
  { name: "Noto Sans Limbu", isLoaded: false },
  { name: "Noto Sans Linear A", isLoaded: false },
  { name: "Noto Sans Linear B", isLoaded: false },
  { name: "Noto Sans Lisu", isLoaded: false },
  { name: "Noto Sans Lycian", isLoaded: false },
  { name: "Noto Sans Lydian", isLoaded: false },
  { name: "Noto Sans Mahajani", isLoaded: false },
  { name: "Noto Sans Malayalam", isLoaded: false },
  { name: "Noto Sans Mandaic", isLoaded: false },
  { name: "Noto Sans Manichaean", isLoaded: false },
  { name: "Noto Sans Marchen", isLoaded: false },
  { name: "Noto Sans Masaram Gondi", isLoaded: false },
  { name: "Noto Sans Math", isLoaded: false },
  { name: "Noto Sans Mayan Numerals", isLoaded: false },
  { name: "Noto Sans Medefaidrin", isLoaded: false },
  { name: "Noto Sans Meetei Mayek", isLoaded: false },
  { name: "Noto Sans Mende Kikakui", isLoaded: false },
  { name: "Noto Sans Meroitic", isLoaded: false },
  { name: "Noto Sans Miao", isLoaded: false },
  { name: "Noto Sans Modi", isLoaded: false },
  { name: "Noto Sans Mongolian", isLoaded: false },
  { name: "Noto Sans Mono", isLoaded: false },
  { name: "Noto Sans Mro", isLoaded: false },
  { name: "Noto Sans Multani", isLoaded: false },
  { name: "Noto Sans Myanmar", isLoaded: false },
  { name: "Noto Sans NKo", isLoaded: false },
  { name: "Noto Sans NKo Unjoined", isLoaded: false },
  { name: "Noto Sans Nabataean", isLoaded: false },
  { name: "Noto Sans Nag Mundari", isLoaded: false },
  { name: "Noto Sans Nandinagari", isLoaded: false },
  { name: "Noto Sans New Tai Lue", isLoaded: false },
  { name: "Noto Sans Newa", isLoaded: false },
  { name: "Noto Sans Nushu", isLoaded: false },
  { name: "Noto Sans Ogham", isLoaded: false },
  { name: "Noto Sans Ol Chiki", isLoaded: false },
  { name: "Noto Sans Old Hungarian", isLoaded: false },
  { name: "Noto Sans Old Italic", isLoaded: false },
  { name: "Noto Sans Old North Arabian", isLoaded: false },
  { name: "Noto Sans Old Permic", isLoaded: false },
  { name: "Noto Sans Old Persian", isLoaded: false },
  { name: "Noto Sans Old Sogdian", isLoaded: false },
  { name: "Noto Sans Old South Arabian", isLoaded: false },
  { name: "Noto Sans Old Turkic", isLoaded: false },
  { name: "Noto Sans Oriya", isLoaded: false },
  { name: "Noto Sans Osage", isLoaded: false },
  { name: "Noto Sans Osmanya", isLoaded: false },
  { name: "Noto Sans Pahawh Hmong", isLoaded: false },
  { name: "Noto Sans Palmyrene", isLoaded: false },
  { name: "Noto Sans Pau Cin Hau", isLoaded: false },
  { name: "Noto Sans Phags Pa", isLoaded: false },
  { name: "Noto Sans Phoenician", isLoaded: false },
  { name: "Noto Sans Psalter Pahlavi", isLoaded: false },
  { name: "Noto Sans Rejang", isLoaded: false },
  { name: "Noto Sans Runic", isLoaded: false },
  { name: "Noto Sans SC", isLoaded: false },
  { name: "Noto Sans Samaritan", isLoaded: false },
  { name: "Noto Sans Saurashtra", isLoaded: false },
  { name: "Noto Sans Sharada", isLoaded: false },
  { name: "Noto Sans Shavian", isLoaded: false },
  { name: "Noto Sans Siddham", isLoaded: false },
  { name: "Noto Sans SignWriting", isLoaded: false },
  { name: "Noto Sans Sinhala", isLoaded: false },
  { name: "Noto Sans Sogdian", isLoaded: false },
  { name: "Noto Sans Sora Sompeng", isLoaded: false },
  { name: "Noto Sans Soyombo", isLoaded: false },
  { name: "Noto Sans Sundanese", isLoaded: false },
  { name: "Noto Sans Syloti Nagri", isLoaded: false },
  { name: "Noto Sans Symbols", isLoaded: false },
  { name: "Noto Sans Symbols 2", isLoaded: false },
  { name: "Noto Sans Syriac", isLoaded: false },
  { name: "Noto Sans Syriac Eastern", isLoaded: false },
  { name: "Noto Sans TC", isLoaded: false },
  { name: "Noto Sans Tagalog", isLoaded: false },
  { name: "Noto Sans Tagbanwa", isLoaded: false },
  { name: "Noto Sans Tai Le", isLoaded: false },
  { name: "Noto Sans Tai Tham", isLoaded: false },
  { name: "Noto Sans Tai Viet", isLoaded: false },
  { name: "Noto Sans Takri", isLoaded: false },
  { name: "Noto Sans Tamil", isLoaded: false },
  { name: "Noto Sans Tamil Supplement", isLoaded: false },
  { name: "Noto Sans Tangsa", isLoaded: false },
  { name: "Noto Sans Telugu", isLoaded: false },
  { name: "Noto Sans Thaana", isLoaded: false },
  { name: "Noto Sans Thai", isLoaded: false },
  { name: "Noto Sans Thai Looped", isLoaded: false },
  { name: "Noto Sans Tifinagh", isLoaded: false },
  { name: "Noto Sans Tirhuta", isLoaded: false },
  { name: "Noto Sans Ugaritic", isLoaded: false },
  { name: "Noto Sans Vai", isLoaded: false },
  { name: "Noto Sans Vithkuqi", isLoaded: false },
  { name: "Noto Sans Wancho", isLoaded: false },
  { name: "Noto Sans Warang Citi", isLoaded: false },
  { name: "Noto Sans Yi", isLoaded: false },
  { name: "Noto Sans Zanabazar Square", isLoaded: false },
  { name: "Noto Serif", isLoaded: false },
  { name: "Noto Serif Ahom", isLoaded: false },
  { name: "Noto Serif Armenian", isLoaded: false },
  { name: "Noto Serif Balinese", isLoaded: false },
  { name: "Noto Serif Bengali", isLoaded: false },
  { name: "Noto Serif Devanagari", isLoaded: false },
  { name: "Noto Serif Display", isLoaded: false },
  { name: "Noto Serif Dogra", isLoaded: false },
  { name: "Noto Serif Ethiopic", isLoaded: false },
  { name: "Noto Serif Georgian", isLoaded: false },
  { name: "Noto Serif Grantha", isLoaded: false },
  { name: "Noto Serif Gujarati", isLoaded: false },
  { name: "Noto Serif Gurmukhi", isLoaded: false },
  { name: "Noto Serif HK", isLoaded: false },
  { name: "Noto Serif Hebrew", isLoaded: false },
  { name: "Noto Serif JP", isLoaded: false },
  { name: "Noto Serif KR", isLoaded: false },
  { name: "Noto Serif Kannada", isLoaded: false },
  { name: "Noto Serif Khitan Small Script", isLoaded: false },
  { name: "Noto Serif Khmer", isLoaded: false },
  { name: "Noto Serif Khojki", isLoaded: false },
  { name: "Noto Serif Lao", isLoaded: false },
  { name: "Noto Serif Makasar", isLoaded: false },
  { name: "Noto Serif Malayalam", isLoaded: false },
  { name: "Noto Serif Myanmar", isLoaded: false },
  { name: "Noto Serif NP Hmong", isLoaded: false },
  { name: "Noto Serif Oriya", isLoaded: false },
  { name: "Noto Serif Ottoman Siyaq", isLoaded: false },
  { name: "Noto Serif SC", isLoaded: false },
  { name: "Noto Serif Sinhala", isLoaded: false },
  { name: "Noto Serif TC", isLoaded: false },
  { name: "Noto Serif Tamil", isLoaded: false },
  { name: "Noto Serif Tangut", isLoaded: false },
  { name: "Noto Serif Telugu", isLoaded: false },
  { name: "Noto Serif Thai", isLoaded: false },
  { name: "Noto Serif Tibetan", isLoaded: false },
  { name: "Noto Serif Toto", isLoaded: false },
  { name: "Noto Serif Vithkuqi", isLoaded: false },
  { name: "Noto Serif Yezidi", isLoaded: false },
  { name: "Noto Traditional Nushu", isLoaded: false },
  { name: "Nova Cut", isLoaded: false },
  { name: "Nova Flat", isLoaded: false },
  { name: "Nova Mono", isLoaded: false },
  { name: "Nova Oval", isLoaded: false },
  { name: "Nova Round", isLoaded: false },
  { name: "Nova Script", isLoaded: false },
  { name: "Nova Slim", isLoaded: false },
  { name: "Nova Square", isLoaded: false },
  { name: "Numans", isLoaded: false },
  { name: "Nunito", isLoaded: false },
  { name: "Nunito Sans", isLoaded: false },
  { name: "Nuosu SIL", isLoaded: false },
  { name: "Odibee Sans", isLoaded: false },
  { name: "Odor Mean Chey", isLoaded: false },
  { name: "Offside", isLoaded: false },
  { name: "Oi", isLoaded: false },
  { name: "Old Standard TT", isLoaded: false },
  { name: "Oldenburg", isLoaded: false },
  { name: "Ole", isLoaded: false },
  { name: "Oleo Script", isLoaded: false },
  { name: "Oleo Script Swash Caps", isLoaded: false },
  { name: "Onest", isLoaded: false },
  { name: "Oooh Baby", isLoaded: false },
  { name: "Open Sans", isLoaded: false },
  { name: "Oranienbaum", isLoaded: false },
  { name: "Orbit", isLoaded: false },
  { name: "Orbitron", isLoaded: false },
  { name: "Oregano", isLoaded: false },
  { name: "Orelega One", isLoaded: false },
  { name: "Orienta", isLoaded: false },
  { name: "Original Surfer", isLoaded: false },
  { name: "Oswald", isLoaded: false },
  { name: "Outfit", isLoaded: false },
  { name: "Over the Rainbow", isLoaded: false },
  { name: "Overlock", isLoaded: false },
  { name: "Overlock SC", isLoaded: false },
  { name: "Overpass", isLoaded: false },
  { name: "Overpass Mono", isLoaded: false },
  { name: "Ovo", isLoaded: false },
  { name: "Oxanium", isLoaded: false },
  { name: "Oxygen", isLoaded: false },
  { name: "Oxygen Mono", isLoaded: false },
  { name: "PT Mono", isLoaded: false },
  { name: "PT Sans", isLoaded: false },
  { name: "PT Sans Caption", isLoaded: false },
  { name: "PT Sans Narrow", isLoaded: false },
  { name: "PT Serif", isLoaded: false },
  { name: "PT Serif Caption", isLoaded: false },
  { name: "Pacifico", isLoaded: false },
  { name: "Padauk", isLoaded: false },
  { name: "Padyakke Expanded One", isLoaded: false },
  { name: "Palanquin", isLoaded: false },
  { name: "Palanquin Dark", isLoaded: false },
  { name: "Palette Mosaic", isLoaded: false },
  { name: "Pangolin", isLoaded: false },
  { name: "Paprika", isLoaded: false },
  { name: "Parisienne", isLoaded: false },
  { name: "Passero One", isLoaded: false },
  { name: "Passion One", isLoaded: false },
  { name: "Passions Conflict", isLoaded: false },
  { name: "Pathway Extreme", isLoaded: false },
  { name: "Pathway Gothic One", isLoaded: false },
  { name: "Patrick Hand", isLoaded: false },
  { name: "Patrick Hand SC", isLoaded: false },
  { name: "Pattaya", isLoaded: false },
  { name: "Patua One", isLoaded: false },
  { name: "Pavanam", isLoaded: false },
  { name: "Paytone One", isLoaded: false },
  { name: "Peddana", isLoaded: false },
  { name: "Peralta", isLoaded: false },
  { name: "Permanent Marker", isLoaded: false },
  { name: "Petemoss", isLoaded: false },
  { name: "Petit Formal Script", isLoaded: false },
  { name: "Petrona", isLoaded: false },
  { name: "Philosopher", isLoaded: false },
  { name: "Phudu", isLoaded: false },
  { name: "Piazzolla", isLoaded: false },
  { name: "Piedra", isLoaded: false },
  { name: "Pinyon Script", isLoaded: false },
  { name: "Pirata One", isLoaded: false },
  { name: "Pixelify Sans", isLoaded: false },
  { name: "Plaster", isLoaded: false },
  { name: "Play", isLoaded: false },
  { name: "Playball", isLoaded: false },
  { name: "Playfair", isLoaded: false },
  { name: "Playfair Display", isLoaded: false },
  { name: "Playfair Display SC", isLoaded: false },
  { name: "Playpen Sans", isLoaded: false },
  { name: "Plus Jakarta Sans", isLoaded: false },
  { name: "Podkova", isLoaded: false },
  { name: "Poiret One", isLoaded: false },
  { name: "Poller One", isLoaded: false },
  { name: "Poltawski Nowy", isLoaded: false },
  { name: "Poly", isLoaded: false },
  { name: "Pompiere", isLoaded: false },
  { name: "Pontano Sans", isLoaded: false },
  { name: "Poor Story", isLoaded: false },
  { name: "Poppins", isLoaded: false },
  { name: "Port Lligat Sans", isLoaded: false },
  { name: "Port Lligat Slab", isLoaded: false },
  { name: "Potta One", isLoaded: false },
  { name: "Pragati Narrow", isLoaded: false },
  { name: "Praise", isLoaded: false },
  { name: "Prata", isLoaded: false },
  { name: "Preahvihear", isLoaded: false },
  { name: "Press Start 2P", isLoaded: false },
  { name: "Pridi", isLoaded: false },
  { name: "Princess Sofia", isLoaded: false },
  { name: "Prociono", isLoaded: false },
  { name: "Prompt", isLoaded: false },
  { name: "Prosto One", isLoaded: false },
  { name: "Proza Libre", isLoaded: false },
  { name: "Public Sans", isLoaded: false },
  { name: "Puppies Play", isLoaded: false },
  { name: "Puritan", isLoaded: false },
  { name: "Purple Purse", isLoaded: false },
  { name: "Qahiri", isLoaded: false },
  { name: "Quando", isLoaded: false },
  { name: "Quantico", isLoaded: false },
  { name: "Quattrocento", isLoaded: false },
  { name: "Quattrocento Sans", isLoaded: false },
  { name: "Questrial", isLoaded: false },
  { name: "Quicksand", isLoaded: false },
  { name: "Quintessential", isLoaded: false },
  { name: "Qwigley", isLoaded: false },
  { name: "Qwitcher Grypen", isLoaded: false },
  { name: "REM", isLoaded: false },
  { name: "Racing Sans One", isLoaded: false },
  { name: "Radio Canada", isLoaded: false },
  { name: "Radley", isLoaded: false },
  { name: "Rajdhani", isLoaded: false },
  { name: "Rakkas", isLoaded: false },
  { name: "Raleway", isLoaded: false },
  { name: "Raleway Dots", isLoaded: false },
  { name: "Ramabhadra", isLoaded: false },
  { name: "Ramaraja", isLoaded: false },
  { name: "Rambla", isLoaded: false },
  { name: "Rammetto One", isLoaded: false },
  { name: "Rampart One", isLoaded: false },
  { name: "Ranchers", isLoaded: false },
  { name: "Rancho", isLoaded: false },
  { name: "Ranga", isLoaded: false },
  { name: "Rasa", isLoaded: false },
  { name: "Rationale", isLoaded: false },
  { name: "Ravi Prakash", isLoaded: false },
  { name: "Readex Pro", isLoaded: false },
  { name: "Recursive", isLoaded: false },
  { name: "Red Hat Display", isLoaded: false },
  { name: "Red Hat Mono", isLoaded: false },
  { name: "Red Hat Text", isLoaded: false },
  { name: "Red Rose", isLoaded: false },
  { name: "Redacted", isLoaded: false },
  { name: "Redacted Script", isLoaded: false },
  { name: "Redressed", isLoaded: false },
  { name: "Reem Kufi", isLoaded: false },
  { name: "Reem Kufi Fun", isLoaded: false },
  { name: "Reem Kufi Ink", isLoaded: false },
  { name: "Reenie Beanie", isLoaded: false },
  { name: "Reggae One", isLoaded: false },
  { name: "Revalia", isLoaded: false },
  { name: "Rhodium Libre", isLoaded: false },
  { name: "Ribeye", isLoaded: false },
  { name: "Ribeye Marrow", isLoaded: false },
  { name: "Righteous", isLoaded: false },
  { name: "Risque", isLoaded: false },
  { name: "Road Rage", isLoaded: false },
  { name: "Roboto", isLoaded: false },
  { name: "Roboto Condensed", isLoaded: false },
  { name: "Roboto Flex", isLoaded: false },
  { name: "Roboto Mono", isLoaded: false },
  { name: "Roboto Serif", isLoaded: false },
  { name: "Roboto Slab", isLoaded: false },
  { name: "Rochester", isLoaded: false },
  { name: "Rock 3D", isLoaded: false },
  { name: "Rock Salt", isLoaded: false },
  { name: "RocknRoll One", isLoaded: false },
  { name: "Rokkitt", isLoaded: false },
  { name: "Romanesco", isLoaded: false },
  { name: "Ropa Sans", isLoaded: false },
  { name: "Rosario", isLoaded: false },
  { name: "Rosarivo", isLoaded: false },
  { name: "Rouge Script", isLoaded: false },
  { name: "Rowdies", isLoaded: false },
  { name: "Rozha One", isLoaded: false },
  { name: "Rubik", isLoaded: false },
  { name: "Rubik 80s Fade", isLoaded: false },
  { name: "Rubik Beastly", isLoaded: false },
  { name: "Rubik Bubbles", isLoaded: false },
  { name: "Rubik Burned", isLoaded: false },
  { name: "Rubik Dirt", isLoaded: false },
  { name: "Rubik Distressed", isLoaded: false },
  { name: "Rubik Gemstones", isLoaded: false },
  { name: "Rubik Glitch", isLoaded: false },
  { name: "Rubik Iso", isLoaded: false },
  { name: "Rubik Marker Hatch", isLoaded: false },
  { name: "Rubik Maze", isLoaded: false },
  { name: "Rubik Microbe", isLoaded: false },
  { name: "Rubik Mono One", isLoaded: false },
  { name: "Rubik Moonrocks", isLoaded: false },
  { name: "Rubik Pixels", isLoaded: false },
  { name: "Rubik Puddles", isLoaded: false },
  { name: "Rubik Spray Paint", isLoaded: false },
  { name: "Rubik Storm", isLoaded: false },
  { name: "Rubik Vinyl", isLoaded: false },
  { name: "Rubik Wet Paint", isLoaded: false },
  { name: "Ruda", isLoaded: false },
  { name: "Rufina", isLoaded: false },
  { name: "Ruge Boogie", isLoaded: false },
  { name: "Ruluko", isLoaded: false },
  { name: "Rum Raisin", isLoaded: false },
  { name: "Ruslan Display", isLoaded: false },
  { name: "Russo One", isLoaded: false },
  { name: "Ruthie", isLoaded: false },
  { name: "Ruwudu", isLoaded: false },
  { name: "Rye", isLoaded: false },
  { name: "STIX Two Text", isLoaded: false },
  { name: "Sacramento", isLoaded: false },
  { name: "Sahitya", isLoaded: false },
  { name: "Sail", isLoaded: false },
  { name: "Saira", isLoaded: false },
  { name: "Saira Condensed", isLoaded: false },
  { name: "Saira Extra Condensed", isLoaded: false },
  { name: "Saira Semi Condensed", isLoaded: false },
  { name: "Saira Stencil One", isLoaded: false },
  { name: "Salsa", isLoaded: false },
  { name: "Sanchez", isLoaded: false },
  { name: "Sancreek", isLoaded: false },
  { name: "Sansita", isLoaded: false },
  { name: "Sansita Swashed", isLoaded: false },
  { name: "Sarabun", isLoaded: false },
  { name: "Sarala", isLoaded: false },
  { name: "Sarina", isLoaded: false },
  { name: "Sarpanch", isLoaded: false },
  { name: "Sassy Frass", isLoaded: false },
  { name: "Satisfy", isLoaded: false },
  { name: "Sawarabi Gothic", isLoaded: false },
  { name: "Sawarabi Mincho", isLoaded: false },
  { name: "Scada", isLoaded: false },
  { name: "Scheherazade New", isLoaded: false },
  { name: "Schibsted Grotesk", isLoaded: false },
  { name: "Schoolbell", isLoaded: false },
  { name: "Scope One", isLoaded: false },
  { name: "Seaweed Script", isLoaded: false },
  { name: "Secular One", isLoaded: false },
  { name: "Sedgwick Ave", isLoaded: false },
  { name: "Sedgwick Ave Display", isLoaded: false },
  { name: "Sen", isLoaded: false },
  { name: "Send Flowers", isLoaded: false },
  { name: "Sevillana", isLoaded: false },
  { name: "Seymour One", isLoaded: false },
  { name: "Shadows Into Light", isLoaded: false },
  { name: "Shadows Into Light Two", isLoaded: false },
  { name: "Shalimar", isLoaded: false },
  { name: "Shantell Sans", isLoaded: false },
  { name: "Shanti", isLoaded: false },
  { name: "Share", isLoaded: false },
  { name: "Share Tech", isLoaded: false },
  { name: "Share Tech Mono", isLoaded: false },
  { name: "Shippori Antique", isLoaded: false },
  { name: "Shippori Antique B1", isLoaded: false },
  { name: "Shippori Mincho", isLoaded: false },
  { name: "Shippori Mincho B1", isLoaded: false },
  { name: "Shizuru", isLoaded: false },
  { name: "Shojumaru", isLoaded: false },
  { name: "Short Stack", isLoaded: false },
  { name: "Shrikhand", isLoaded: false },
  { name: "Siemreap", isLoaded: false },
  { name: "Sigmar", isLoaded: false },
  { name: "Sigmar One", isLoaded: false },
  { name: "Signika", isLoaded: false },
  { name: "Signika Negative", isLoaded: false },
  { name: "Silkscreen", isLoaded: false },
  { name: "Simonetta", isLoaded: false },
  { name: "Single Day", isLoaded: false },
  { name: "Sintony", isLoaded: false },
  { name: "Sirin Stencil", isLoaded: false },
  { name: "Six Caps", isLoaded: false },
  { name: "Skranji", isLoaded: false },
  { name: "Slabo 13px", isLoaded: false },
  { name: "Slabo 27px", isLoaded: false },
  { name: "Slackey", isLoaded: false },
  { name: "Slackside One", isLoaded: false },
  { name: "Smokum", isLoaded: false },
  { name: "Smooch", isLoaded: false },
  { name: "Smooch Sans", isLoaded: false },
  { name: "Smythe", isLoaded: false },
  { name: "Sniglet", isLoaded: false },
  { name: "Snippet", isLoaded: false },
  { name: "Snowburst One", isLoaded: false },
  { name: "Sofadi One", isLoaded: false },
  { name: "Sofia", isLoaded: false },
  { name: "Sofia Sans", isLoaded: false },
  { name: "Sofia Sans Condensed", isLoaded: false },
  { name: "Sofia Sans Extra Condensed", isLoaded: false },
  { name: "Sofia Sans Semi Condensed", isLoaded: false },
  { name: "Solitreo", isLoaded: false },
  { name: "Solway", isLoaded: false },
  { name: "Sometype Mono", isLoaded: false },
  { name: "Song Myung", isLoaded: false },
  { name: "Sono", isLoaded: false },
  { name: "Sonsie One", isLoaded: false },
  { name: "Sora", isLoaded: false },
  { name: "Sorts Mill Goudy", isLoaded: false },
  { name: "Source Code Pro", isLoaded: false },
  { name: "Source Sans 3", isLoaded: false },
  { name: "Source Serif 4", isLoaded: false },
  { name: "Space Grotesk", isLoaded: false },
  { name: "Space Mono", isLoaded: false },
  { name: "Special Elite", isLoaded: false },
  { name: "Spectral", isLoaded: false },
  { name: "Spectral SC", isLoaded: false },
  { name: "Spicy Rice", isLoaded: false },
  { name: "Spinnaker", isLoaded: false },
  { name: "Spirax", isLoaded: false },
  { name: "Splash", isLoaded: false },
  { name: "Spline Sans", isLoaded: false },
  { name: "Spline Sans Mono", isLoaded: false },
  { name: "Squada One", isLoaded: false },
  { name: "Square Peg", isLoaded: false },
  { name: "Sree Krushnadevaraya", isLoaded: false },
  { name: "Sriracha", isLoaded: false },
  { name: "Srisakdi", isLoaded: false },
  { name: "Staatliches", isLoaded: false },
  { name: "Stalemate", isLoaded: false },
  { name: "Stalinist One", isLoaded: false },
  { name: "Stardos Stencil", isLoaded: false },
  { name: "Stick", isLoaded: false },
  { name: "Stick No Bills", isLoaded: false },
  { name: "Stint Ultra Condensed", isLoaded: false },
  { name: "Stint Ultra Expanded", isLoaded: false },
  { name: "Stoke", isLoaded: false },
  { name: "Strait", isLoaded: false },
  { name: "Style Script", isLoaded: false },
  { name: "Stylish", isLoaded: false },
  { name: "Sue Ellen Francisco", isLoaded: false },
  { name: "Suez One", isLoaded: false },
  { name: "Sulphur Point", isLoaded: false },
  { name: "Sumana", isLoaded: false },
  { name: "Sunflower", isLoaded: false },
  { name: "Sunshiney", isLoaded: false },
  { name: "Supermercado One", isLoaded: false },
  { name: "Sura", isLoaded: false },
  { name: "Suranna", isLoaded: false },
  { name: "Suravaram", isLoaded: false },
  { name: "Suwannaphum", isLoaded: false },
  { name: "Swanky and Moo Moo", isLoaded: false },
  { name: "Syncopate", isLoaded: false },
  { name: "Syne", isLoaded: false },
  { name: "Syne Mono", isLoaded: false },
  { name: "Syne Tactile", isLoaded: false },
  { name: "Tai Heritage Pro", isLoaded: false },
  { name: "Tajawal", isLoaded: false },
  { name: "Tangerine", isLoaded: false },
  { name: "Tapestry", isLoaded: false },
  { name: "Taprom", isLoaded: false },
  { name: "Tauri", isLoaded: false },
  { name: "Taviraj", isLoaded: false },
  { name: "Teko", isLoaded: false },
  { name: "Tektur", isLoaded: false },
  { name: "Telex", isLoaded: false },
  { name: "Tenali Ramakrishna", isLoaded: false },
  { name: "Tenor Sans", isLoaded: false },
  { name: "Text Me One", isLoaded: false },
  { name: "Texturina", isLoaded: false },
  { name: "Thasadith", isLoaded: false },
  { name: "The Girl Next Door", isLoaded: false },
  { name: "The Nautigal", isLoaded: false },
  { name: "Tienne", isLoaded: false },
  { name: "Tillana", isLoaded: false },
  { name: "Tilt Neon", isLoaded: false },
  { name: "Tilt Prism", isLoaded: false },
  { name: "Tilt Warp", isLoaded: false },
  { name: "Timmana", isLoaded: false },
  { name: "Tinos", isLoaded: false },
  { name: "Tiro Bangla", isLoaded: false },
  { name: "Tiro Devanagari Hindi", isLoaded: false },
  { name: "Tiro Devanagari Marathi", isLoaded: false },
  { name: "Tiro Devanagari Sanskrit", isLoaded: false },
  { name: "Tiro Gurmukhi", isLoaded: false },
  { name: "Tiro Kannada", isLoaded: false },
  { name: "Tiro Tamil", isLoaded: false },
  { name: "Tiro Telugu", isLoaded: false },
  { name: "Titan One", isLoaded: false },
  { name: "Titillium Web", isLoaded: false },
  { name: "Tomorrow", isLoaded: false },
  { name: "Tourney", isLoaded: false },
  { name: "Trade Winds", isLoaded: false },
  { name: "Train One", isLoaded: false },
  { name: "Trirong", isLoaded: false },
  { name: "Trispace", isLoaded: false },
  { name: "Trocchi", isLoaded: false },
  { name: "Trochut", isLoaded: false },
  { name: "Truculenta", isLoaded: false },
  { name: "Trykker", isLoaded: false },
  { name: "Tsukimi Rounded", isLoaded: false },
  { name: "Tulpen One", isLoaded: false },
  { name: "Turret Road", isLoaded: false },
  { name: "Twinkle Star", isLoaded: false },
  { name: "Ubuntu", isLoaded: false },
  { name: "Ubuntu Condensed", isLoaded: false },
  { name: "Ubuntu Mono", isLoaded: false },
  { name: "Uchen", isLoaded: false },
  { name: "Ultra", isLoaded: false },
  { name: "Unbounded", isLoaded: false },
  { name: "Uncial Antiqua", isLoaded: false },
  { name: "Underdog", isLoaded: false },
  { name: "Unica One", isLoaded: false },
  { name: "UnifrakturCook", isLoaded: false },
  { name: "UnifrakturMaguntia", isLoaded: false },
  { name: "Unkempt", isLoaded: false },
  { name: "Unlock", isLoaded: false },
  { name: "Unna", isLoaded: false },
  { name: "Updock", isLoaded: false },
  { name: "Urbanist", isLoaded: false },
  { name: "VT323", isLoaded: false },
  { name: "Vampiro One", isLoaded: false },
  { name: "Varela", isLoaded: false },
  { name: "Varela Round", isLoaded: false },
  { name: "Varta", isLoaded: false },
  { name: "Vast Shadow", isLoaded: false },
  { name: "Vazirmatn", isLoaded: false },
  { name: "Vesper Libre", isLoaded: false },
  { name: "Viaoda Libre", isLoaded: false },
  { name: "Vibes", isLoaded: false },
  { name: "Vibur", isLoaded: false },
  { name: "Victor Mono", isLoaded: false },
  { name: "Vidaloka", isLoaded: false },
  { name: "Viga", isLoaded: false },
  { name: "Vina Sans", isLoaded: false },
  { name: "Voces", isLoaded: false },
  { name: "Volkhov", isLoaded: false },
  { name: "Vollkorn", isLoaded: false },
  { name: "Vollkorn SC", isLoaded: false },
  { name: "Voltaire", isLoaded: false },
  { name: "Vujahday Script", isLoaded: false },
  { name: "Waiting for the Sunrise", isLoaded: false },
  { name: "Wallpoet", isLoaded: false },
  { name: "Walter Turncoat", isLoaded: false },
  { name: "Warnes", isLoaded: false },
  { name: "Water Brush", isLoaded: false },
  { name: "Waterfall", isLoaded: false },
  { name: "Wavefont", isLoaded: false },
  { name: "Wellfleet", isLoaded: false },
  { name: "Wendy One", isLoaded: false },
  { name: "Whisper", isLoaded: false },
  { name: "WindSong", isLoaded: false },
  { name: "Wire One", isLoaded: false },
  { name: "Wix Madefor Display", isLoaded: false },
  { name: "Wix Madefor Text", isLoaded: false },
  { name: "Work Sans", isLoaded: false },
  { name: "Xanh Mono", isLoaded: false },
  { name: "Yaldevi", isLoaded: false },
  { name: "Yanone Kaffeesatz", isLoaded: false },
  { name: "Yantramanav", isLoaded: false },
  { name: "Yatra One", isLoaded: false },
  { name: "Yellowtail", isLoaded: false },
  { name: "Yeon Sung", isLoaded: false },
  { name: "Yeseva One", isLoaded: false },
  { name: "Yesteryear", isLoaded: false },
  { name: "Yomogi", isLoaded: false },
  { name: "Young Serif", isLoaded: false },
  { name: "Yrsa", isLoaded: false },
  { name: "Ysabeau", isLoaded: false },
  { name: "Ysabeau Infant", isLoaded: false },
  { name: "Ysabeau Office", isLoaded: false },
  { name: "Ysabeau SC", isLoaded: false },
  { name: "Yuji Boku", isLoaded: false },
  { name: "Yuji Hentaigana Akari", isLoaded: false },
  { name: "Yuji Hentaigana Akebono", isLoaded: false },
  { name: "Yuji Mai", isLoaded: false },
  { name: "Yuji Syuku", isLoaded: false },
  { name: "Yusei Magic", isLoaded: false },
  { name: "ZCOOL KuaiLe", isLoaded: false },
  { name: "ZCOOL QingKe HuangYou", isLoaded: false },
  { name: "ZCOOL XiaoWei", isLoaded: false },
  { name: "Zen Antique", isLoaded: false },
  { name: "Zen Antique Soft", isLoaded: false },
  { name: "Zen Dots", isLoaded: false },
  { name: "Zen Kaku Gothic Antique", isLoaded: false },
  { name: "Zen Kaku Gothic New", isLoaded: false },
  { name: "Zen Kurenaido", isLoaded: false },
  { name: "Zen Loop", isLoaded: false },
  { name: "Zen Maru Gothic", isLoaded: false },
  { name: "Zen Old Mincho", isLoaded: false },
  { name: "Zen Tokyo Zoo", isLoaded: false },
  { name: "Zeyada", isLoaded: false },
  { name: "Zhi Mang Xing", isLoaded: false },
  { name: "Zilla Slab", isLoaded: false },
  { name: "Zilla Slab Highlight", isLoaded: false },
];
document.addEventListener("DOMContentLoaded", () => {
  fontFamilies.forEach((fontFamily) => {
    const optionElement = document.createElement("option");
    optionElement.value = fontFamily.name;
    optionElement.textContent = fontFamily.name;
    fontFamilySelectElement.appendChild(optionElement);
  });
  fontFamilySelectElement.value = "Atkinson Hyperlegible Next";
});
fontFamilySelectElement.addEventListener("change", (event) => {
  const selectedFontFamilyName = event.target.value;
  const selectedFontFamily = fontFamilies.find(
    (fontFamily) => fontFamily.name === selectedFontFamilyName
  );
  // Load from google fonts
  if (!selectedFontFamily.isLoaded) {
    const linkElement = document.createElement("link");
    linkElement.rel = "stylesheet";
    linkElement.href = `https://fonts.googleapis.com/css2?family=${selectedFontFamilyName.replace(
      " ",
      "+"
    )}&display=swap`;
    document.head.appendChild(linkElement);
    selectedFontFamily.isLoaded = true;
  }
  document.querySelector("article").style.fontFamily = selectedFontFamilyName;
});

ratioValueInputElement.addEventListener("input", (event) => {
  const customRatio = parseFloat(event.target.value);
  if (!isNaN(customRatio) && customRatio > 1) {
    document
      .querySelector(".custom-ratio")
      .style.setProperty("--multiplier", customRatio);
  } else {
    console.warn("Invalid custom ratio value");
  }
});
